// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_humArc;
extern lv_obj_t * ui_HumVal;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_tempArc;
extern lv_obj_t * ui_tempVal;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_O3Arc;
extern lv_obj_t * ui_O3Val;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_So2Arc;
extern lv_obj_t * ui_So2Val;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_No2Arc;
extern lv_obj_t * ui_No2Val;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_CoArc;
extern lv_obj_t * ui_CoVal;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Co2Arc;
extern lv_obj_t * ui_Co2Val;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_timeVal2;
extern lv_obj_t * ui_dateval;
extern lv_obj_t * ui_Panel16;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_VOC_Value;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image7;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

