// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_humArc = NULL;
lv_obj_t * ui_HumVal = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_tempArc = NULL;
lv_obj_t * ui_tempVal = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_O3Arc = NULL;
lv_obj_t * ui_O3Val = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_So2Arc = NULL;
lv_obj_t * ui_So2Val = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_No2Arc = NULL;
lv_obj_t * ui_No2Val = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_CoArc = NULL;
lv_obj_t * ui_CoVal = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Co2Arc = NULL;
lv_obj_t * ui_Co2Val = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_timeVal2 = NULL;
lv_obj_t * ui_dateval = NULL;
lv_obj_t * ui_Panel16 = NULL;
lv_obj_t * ui_Arc1 = NULL;
lv_obj_t * ui_VOC_Value = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
        _ui_screen_delete(&ui_Screen3);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel7 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel7, 462);
    lv_obj_set_height(ui_Panel7, 303);
    lv_obj_set_x(ui_Panel7, -1);
    lv_obj_set_y(ui_Panel7, 0);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel7, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel7, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel9, 188);
    lv_obj_set_height(ui_Panel9, 103);
    lv_obj_set_x(ui_Panel9, -87);
    lv_obj_set_y(ui_Panel9, -31);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel9, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel9, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humArc = lv_arc_create(ui_Panel9);
    lv_obj_set_width(ui_humArc, 84);
    lv_obj_set_height(ui_humArc, 80);
    lv_obj_set_x(ui_humArc, 47);
    lv_obj_set_y(ui_humArc, 5);
    lv_obj_set_align(ui_humArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_humArc, 55);
    lv_arc_set_bg_angles(ui_humArc, 270, 269);

    lv_obj_set_style_shadow_color(ui_humArc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_humArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_humArc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_humArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_humArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_humArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_humArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_HumVal = lv_label_create(ui_humArc);
    lv_obj_set_width(ui_HumVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumVal, -14);
    lv_obj_set_y(ui_HumVal, 0);
    lv_obj_set_align(ui_HumVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumVal, "51.6");
    lv_obj_set_style_text_font(ui_HumVal, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_humArc);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 11);
    lv_obj_set_y(ui_Label11, -1);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "%rh");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempArc = lv_arc_create(ui_Panel9);
    lv_obj_set_width(ui_tempArc, 84);
    lv_obj_set_height(ui_tempArc, 87);
    lv_obj_set_x(ui_tempArc, -46);
    lv_obj_set_y(ui_tempArc, 5);
    lv_obj_set_align(ui_tempArc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tempArc, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_tempArc, LV_SCROLLBAR_MODE_OFF);
    lv_arc_set_value(ui_tempArc, 34);
    lv_arc_set_bg_angles(ui_tempArc, 270, 269);

    lv_obj_set_style_shadow_color(ui_tempArc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_tempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_tempArc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_tempArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_tempArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_tempArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tempArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_tempVal = lv_label_create(ui_tempArc);
    lv_obj_set_width(ui_tempVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempVal, -9);
    lv_obj_set_y(ui_tempVal, 0);
    lv_obj_set_align(ui_tempVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempVal, "34.5");
    lv_obj_set_style_text_font(ui_tempVal, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_tempArc);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 15);
    lv_obj_set_y(ui_Label7, -1);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "°C");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel10, 361);
    lv_obj_set_height(ui_Panel10, 83);
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, 83);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel10, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel10, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel10, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel10, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_O3Arc = lv_arc_create(ui_Panel10);
    lv_obj_set_width(ui_O3Arc, 65);
    lv_obj_set_height(ui_O3Arc, 70);
    lv_obj_set_x(ui_O3Arc, 137);
    lv_obj_set_y(ui_O3Arc, 9);
    lv_obj_set_align(ui_O3Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_O3Arc, 0, 6000);
    lv_arc_set_value(ui_O3Arc, 338);
    lv_obj_set_style_arc_width(ui_O3Arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_O3Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_O3Arc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_O3Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_O3Arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_O3Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_O3Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_O3Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_O3Val = lv_label_create(ui_O3Arc);
    lv_obj_set_width(ui_O3Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_O3Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_O3Val, 1);
    lv_obj_set_y(ui_O3Val, -2);
    lv_obj_set_align(ui_O3Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_O3Val, "338");
    lv_obj_set_style_text_font(ui_O3Val, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_O3Arc);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 16);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "O3");

    ui_So2Arc = lv_arc_create(ui_Panel10);
    lv_obj_set_width(ui_So2Arc, 65);
    lv_obj_set_height(ui_So2Arc, 70);
    lv_obj_set_x(ui_So2Arc, 67);
    lv_obj_set_y(ui_So2Arc, 9);
    lv_obj_set_align(ui_So2Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_So2Arc, 0, 6000);
    lv_arc_set_value(ui_So2Arc, 338);
    lv_obj_set_style_arc_width(ui_So2Arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_So2Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_So2Arc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_So2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_So2Arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_So2Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_So2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_So2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_So2Val = lv_label_create(ui_So2Arc);
    lv_obj_set_width(ui_So2Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_So2Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_So2Val, 1);
    lv_obj_set_y(ui_So2Val, -2);
    lv_obj_set_align(ui_So2Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_So2Val, "338");
    lv_obj_set_style_text_font(ui_So2Val, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_So2Arc);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 16);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "SO2");

    ui_No2Arc = lv_arc_create(ui_Panel10);
    lv_obj_set_width(ui_No2Arc, 65);
    lv_obj_set_height(ui_No2Arc, 70);
    lv_obj_set_x(ui_No2Arc, -1);
    lv_obj_set_y(ui_No2Arc, 9);
    lv_obj_set_align(ui_No2Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_No2Arc, 0, 6000);
    lv_arc_set_value(ui_No2Arc, 338);
    lv_obj_set_style_arc_width(ui_No2Arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_No2Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_No2Arc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_No2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_No2Arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_No2Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_No2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_No2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_No2Val = lv_label_create(ui_No2Arc);
    lv_obj_set_width(ui_No2Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_No2Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_No2Val, 1);
    lv_obj_set_y(ui_No2Val, -2);
    lv_obj_set_align(ui_No2Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_No2Val, "338");
    lv_obj_set_style_text_font(ui_No2Val, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_No2Arc);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, 16);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "NO2");

    ui_CoArc = lv_arc_create(ui_Panel10);
    lv_obj_set_width(ui_CoArc, 65);
    lv_obj_set_height(ui_CoArc, 70);
    lv_obj_set_x(ui_CoArc, -68);
    lv_obj_set_y(ui_CoArc, 9);
    lv_obj_set_align(ui_CoArc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_CoArc, 0, 6000);
    lv_arc_set_value(ui_CoArc, 338);
    lv_obj_set_style_arc_width(ui_CoArc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_CoArc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CoArc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CoArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CoArc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_CoArc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CoArc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CoVal = lv_label_create(ui_CoArc);
    lv_obj_set_width(ui_CoVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CoVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CoVal, 1);
    lv_obj_set_y(ui_CoVal, -2);
    lv_obj_set_align(ui_CoVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CoVal, "338");
    lv_obj_set_style_text_font(ui_CoVal, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_CoArc);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, 16);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "CO");

    ui_Co2Arc = lv_arc_create(ui_Panel10);
    lv_obj_set_width(ui_Co2Arc, 65);
    lv_obj_set_height(ui_Co2Arc, 70);
    lv_obj_set_x(ui_Co2Arc, -137);
    lv_obj_set_y(ui_Co2Arc, 9);
    lv_obj_set_align(ui_Co2Arc, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Co2Arc, 0, 6000);
    lv_arc_set_value(ui_Co2Arc, 338);
    lv_obj_set_style_arc_width(ui_Co2Arc, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Co2Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Co2Arc, lv_color_hex(0x00FFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Co2Arc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Co2Arc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Co2Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Co2Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Co2Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Co2Val = lv_label_create(ui_Co2Arc);
    lv_obj_set_width(ui_Co2Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Co2Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Co2Val, 1);
    lv_obj_set_y(ui_Co2Val, -2);
    lv_obj_set_align(ui_Co2Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Co2Val, "338 ");
    lv_obj_set_style_text_font(ui_Co2Val, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Co2Arc);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, 16);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "CO2");

    ui_Image3 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image3, &ui_img_322445076);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 405
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 124
    lv_obj_set_x(ui_Image3, -173);
    lv_obj_set_y(ui_Image3, -128);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 85);

    ui_Panel8 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel8, 158);
    lv_obj_set_height(ui_Panel8, 21);
    lv_obj_set_x(ui_Panel8, 145);
    lv_obj_set_y(ui_Panel8, -135);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel8, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel8, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeVal2 = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_timeVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeVal2, -41);
    lv_obj_set_y(ui_timeVal2, -1);
    lv_obj_set_align(ui_timeVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeVal2, "12:44:60");
    lv_obj_set_style_text_font(ui_timeVal2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_timeVal2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_timeVal2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_timeVal2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_timeVal2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateval = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_dateval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateval, 33);
    lv_obj_set_y(ui_dateval, -1);
    lv_obj_set_align(ui_dateval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateval, "14/07/2025");
    lv_obj_set_style_text_font(ui_dateval, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dateval, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dateval, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dateval, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel16 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel16, 167);
    lv_obj_set_height(ui_Panel16, 103);
    lv_obj_set_x(ui_Panel16, 101);
    lv_obj_set_y(ui_Panel16, -30);
    lv_obj_set_align(ui_Panel16, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel16, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel16, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel16, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel16, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel16, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Panel16);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_x(ui_Arc1, -3);
    lv_obj_set_y(ui_Arc1, 34);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_Arc1, 0, 400);
    lv_arc_set_value(ui_Arc1, 100);
    lv_arc_set_bg_angles(ui_Arc1, 180, 0);
    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc1, &ui_img_1307048613, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_Arc1, &ui_img_group_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_VOC_Value = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_VOC_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VOC_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VOC_Value, 96);
    lv_obj_set_y(ui_VOC_Value, -28);
    lv_obj_set_align(ui_VOC_Value, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VOC_Value, "400");

    ui_Label12 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 97);
    lv_obj_set_y(ui_Label12, -7);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "VOC");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_Image7, &ui_img_966459430);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_Image7, 46);
    lv_obj_set_y(ui_Image7, -134);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button3 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_Button3, 40);
    lv_obj_set_height(ui_Button3, 25);
    lv_obj_set_x(ui_Button3, -204);
    lv_obj_set_y(ui_Button3, 130);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x00FEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Panel7 = NULL;
    ui_Panel9 = NULL;
    ui_humArc = NULL;
    ui_HumVal = NULL;
    ui_Label11 = NULL;
    ui_tempArc = NULL;
    ui_tempVal = NULL;
    ui_Label7 = NULL;
    ui_Panel10 = NULL;
    ui_O3Arc = NULL;
    ui_O3Val = NULL;
    ui_Label21 = NULL;
    ui_So2Arc = NULL;
    ui_So2Val = NULL;
    ui_Label19 = NULL;
    ui_No2Arc = NULL;
    ui_No2Val = NULL;
    ui_Label17 = NULL;
    ui_CoArc = NULL;
    ui_CoVal = NULL;
    ui_Label15 = NULL;
    ui_Co2Arc = NULL;
    ui_Co2Val = NULL;
    ui_Label13 = NULL;
    ui_Image3 = NULL;
    ui_Panel8 = NULL;
    ui_timeVal2 = NULL;
    ui_dateval = NULL;
    ui_Panel16 = NULL;
    ui_Arc1 = NULL;
    ui_VOC_Value = NULL;
    ui_Label12 = NULL;
    ui_Image7 = NULL;
    ui_Button3 = NULL;

}
