// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: test

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_pm25Arc = NULL;
lv_obj_t * ui_pm25Val = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_pm10Arc = NULL;
lv_obj_t * ui_pm10Val = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_pm4Arc = NULL;
lv_obj_t * ui_pm4Val = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_pm1Arc = NULL;
lv_obj_t * ui_pm1Val = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Panel15 = NULL;
lv_obj_t * ui_timeVal = NULL;
lv_obj_t * ui_dateVal2 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Button1 = NULL;
// event funtions
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_RELEASED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
        _ui_screen_delete(&ui_Screen2);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel5, 462);
    lv_obj_set_height(ui_Panel5, 303);
    lv_obj_set_x(ui_Panel5, 0);
    lv_obj_set_y(ui_Panel5, -1);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel5, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel5, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel4, 167);
    lv_obj_set_height(ui_Panel4, 98);
    lv_obj_set_x(ui_Panel4, -91);
    lv_obj_set_y(ui_Panel4, -31);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel4, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel4, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel4, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm25Arc = lv_arc_create(ui_Panel4);
    lv_obj_set_width(ui_pm25Arc, 150);
    lv_obj_set_height(ui_pm25Arc, 150);
    lv_obj_set_x(ui_pm25Arc, -1);
    lv_obj_set_y(ui_pm25Arc, 33);
    lv_obj_set_align(ui_pm25Arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm25Arc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_pm25Arc, 0, 500);
    lv_arc_set_value(ui_pm25Arc, 20);
    lv_arc_set_bg_angles(ui_pm25Arc, 180, 0);
    lv_obj_set_style_arc_width(ui_pm25Arc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm25Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm25Arc, &ui_img_1307048613, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_pm25Arc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm25Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm25Arc, &ui_img_group_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm25Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm25Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm25Val = lv_label_create(ui_pm25Arc);
    lv_obj_set_width(ui_pm25Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm25Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm25Val, -18);
    lv_obj_set_y(ui_pm25Val, -27);
    lv_obj_set_align(ui_pm25Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm25Val, "800");

    ui_Label30 = lv_label_create(ui_pm25Arc);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 17);
    lv_obj_set_y(ui_Label30, -29);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, "ppm");

    ui_Label3 = lv_label_create(ui_pm25Arc);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, 2);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "PM 2.5");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel1, 167);
    lv_obj_set_height(ui_Panel1, 98);
    lv_obj_set_x(ui_Panel1, 90);
    lv_obj_set_y(ui_Panel1, -31);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel1, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel1, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm10Arc = lv_arc_create(ui_Panel1);
    lv_obj_set_width(ui_pm10Arc, 150);
    lv_obj_set_height(ui_pm10Arc, 150);
    lv_obj_set_x(ui_pm10Arc, -1);
    lv_obj_set_y(ui_pm10Arc, 33);
    lv_obj_set_align(ui_pm10Arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm10Arc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_pm10Arc, 0, 500);
    lv_arc_set_value(ui_pm10Arc, 20);
    lv_arc_set_bg_angles(ui_pm10Arc, 180, 0);
    lv_obj_set_style_arc_width(ui_pm10Arc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm10Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm10Arc, &ui_img_1307048613, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_pm10Arc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm10Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm10Arc, &ui_img_group_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm10Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm10Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm10Val = lv_label_create(ui_pm10Arc);
    lv_obj_set_width(ui_pm10Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm10Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm10Val, -20);
    lv_obj_set_y(ui_pm10Val, -27);
    lv_obj_set_align(ui_pm10Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm10Val, "800");

    ui_Label2 = lv_label_create(ui_pm10Arc);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 16);
    lv_obj_set_y(ui_Label2, -29);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "ppm");

    ui_Label4 = lv_label_create(ui_pm10Arc);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 2);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "PM 10");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel2, 167);
    lv_obj_set_height(ui_Panel2, 98);
    lv_obj_set_x(ui_Panel2, -91);
    lv_obj_set_y(ui_Panel2, 83);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel2, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel2, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm4Arc = lv_arc_create(ui_Panel2);
    lv_obj_set_width(ui_pm4Arc, 150);
    lv_obj_set_height(ui_pm4Arc, 150);
    lv_obj_set_x(ui_pm4Arc, -1);
    lv_obj_set_y(ui_pm4Arc, 33);
    lv_obj_set_align(ui_pm4Arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm4Arc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_pm4Arc, 0, 500);
    lv_arc_set_value(ui_pm4Arc, 20);
    lv_arc_set_bg_angles(ui_pm4Arc, 180, 0);
    lv_obj_set_style_arc_width(ui_pm4Arc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm4Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm4Arc, &ui_img_1307048613, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_pm4Arc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm4Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm4Arc, &ui_img_group_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm4Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm4Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm4Val = lv_label_create(ui_pm4Arc);
    lv_obj_set_width(ui_pm4Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm4Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm4Val, -17);
    lv_obj_set_y(ui_pm4Val, -26);
    lv_obj_set_align(ui_pm4Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm4Val, "800");

    ui_Label31 = lv_label_create(ui_pm4Arc);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 19);
    lv_obj_set_y(ui_Label31, -28);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "ppm");

    ui_Label6 = lv_label_create(ui_pm4Arc);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, 2);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "PM 4");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel5);
    lv_obj_set_width(ui_Panel3, 167);
    lv_obj_set_height(ui_Panel3, 98);
    lv_obj_set_x(ui_Panel3, 90);
    lv_obj_set_y(ui_Panel3, 83);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Panel3, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel3, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel3, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_pm1Arc = lv_arc_create(ui_Panel3);
    lv_obj_set_width(ui_pm1Arc, 150);
    lv_obj_set_height(ui_pm1Arc, 150);
    lv_obj_set_x(ui_pm1Arc, -1);
    lv_obj_set_y(ui_pm1Arc, 33);
    lv_obj_set_align(ui_pm1Arc, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pm1Arc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_arc_set_range(ui_pm1Arc, 0, 500);
    lv_arc_set_value(ui_pm1Arc, 20);
    lv_arc_set_bg_angles(ui_pm1Arc, 180, 0);
    lv_obj_set_style_arc_width(ui_pm1Arc, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm1Arc, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm1Arc, &ui_img_1307048613, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_pm1Arc, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_pm1Arc, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_pm1Arc, &ui_img_group_2_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_pm1Arc, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_pm1Arc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_pm1Val = lv_label_create(ui_pm1Arc);
    lv_obj_set_width(ui_pm1Val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pm1Val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_pm1Val, -18);
    lv_obj_set_y(ui_pm1Val, -26);
    lv_obj_set_align(ui_pm1Val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pm1Val, "800");

    ui_Label8 = lv_label_create(ui_pm1Arc);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, 2);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "PM 1");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_pm1Arc);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 18);
    lv_obj_set_y(ui_Label5, -28);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "ppm");

    ui_Image1 = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_Image1, &ui_img_322445076);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 405
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 124
    lv_obj_set_x(ui_Image1, -173);
    lv_obj_set_y(ui_Image1, -128);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 85);

    ui_Panel15 = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_Panel15, 165);
    lv_obj_set_height(ui_Panel15, 21);
    lv_obj_set_x(ui_Panel15, 142);
    lv_obj_set_y(ui_Panel15, -135);
    lv_obj_set_align(ui_Panel15, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel15, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel15, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Panel15, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Panel15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Panel15, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Panel15, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeVal = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_timeVal, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeVal, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeVal, -43);
    lv_obj_set_y(ui_timeVal, -1);
    lv_obj_set_align(ui_timeVal, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeVal, "12:44:60");
    lv_obj_set_style_text_font(ui_timeVal, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_timeVal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_timeVal, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_timeVal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dateVal2 = lv_label_create(ui_Panel15);
    lv_obj_set_width(ui_dateVal2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dateVal2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dateVal2, 34);
    lv_obj_set_y(ui_dateVal2, -1);
    lv_obj_set_align(ui_dateVal2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dateVal2, "14/07/2025");
    lv_obj_set_style_text_font(ui_dateVal2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dateVal2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dateVal2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dateVal2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image5, &ui_img_966459430);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 22
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 21
    lv_obj_set_x(ui_Image5, 39);
    lv_obj_set_y(ui_Image5, -134);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_Button1, 39);
    lv_obj_set_height(ui_Button1, 26);
    lv_obj_set_x(ui_Button1, 204);
    lv_obj_set_y(ui_Button1, 129);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x00F2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Panel5 = NULL;
    ui_Panel4 = NULL;
    ui_pm25Arc = NULL;
    ui_pm25Val = NULL;
    ui_Label30 = NULL;
    ui_Label3 = NULL;
    ui_Panel1 = NULL;
    ui_pm10Arc = NULL;
    ui_pm10Val = NULL;
    ui_Label2 = NULL;
    ui_Label4 = NULL;
    ui_Panel2 = NULL;
    ui_pm4Arc = NULL;
    ui_pm4Val = NULL;
    ui_Label31 = NULL;
    ui_Label6 = NULL;
    ui_Panel3 = NULL;
    ui_pm1Arc = NULL;
    ui_pm1Val = NULL;
    ui_Label8 = NULL;
    ui_Label5 = NULL;
    ui_Image1 = NULL;
    ui_Panel15 = NULL;
    ui_timeVal = NULL;
    ui_dateVal2 = NULL;
    ui_Image5 = NULL;
    ui_Button1 = NULL;

}
