// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Chart2;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image9;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

