// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: test

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_pm25Arc;
extern lv_obj_t * ui_pm25Val;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_pm10Arc;
extern lv_obj_t * ui_pm10Val;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_pm4Arc;
extern lv_obj_t * ui_pm4Val;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_pm1Arc;
extern lv_obj_t * ui_pm1Val;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Panel15;
extern lv_obj_t * ui_timeVal;
extern lv_obj_t * ui_dateVal2;
extern lv_obj_t * ui_Image5;
extern void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

